### ISSUE TITLE
Feature request - refactor UA parsing to separate module

### ISSUE THREAD

**Issue by lennym** [rguerreiro/express-device#35]
I'm really keen to use this module's functionality, but I only really need the code from https://github.com/rguerreiro/express-device/blob/master/lib/device.js#L48-L106 that maps UA strings to device types.

It'd be really useful if that mapping was separated out into its own module, which this one can then depend on, so the mapping can be used standalone without need for the (unnecessary in my case) coupling to express.

**Comment by lennym** [comment]
As a side note, I'd be happy to do the work on this, but I figured you might want to retain ownership of the child module since you've done all the good work to get it this far.

**Comment by lennym** [comment]
@jimmybergman - any chance you might be open to sharing https://www.npmjs.com/package/device for this purpose?

**Comment by jimmybergman** [comment]
Sure, if done without changing the (tiny) API, then this sounds exactly like what I wanted when depending on express-device in https://github.com/jimmybergman/device

**Comment by lennym** [comment]
@jimmybergman I've thrown together some code at https://github.com/lennym/device/tree/port-express-device-detection-code that does this

*Note: I've changed the license in the package to credit @rguerreiro as the code is all his originally.*

**Comment by jimmybergman** [comment]
@lennym Thanks, I merged this and published as 0.2.0

**Comment by rguerreiro** [comment]
That's something that already crossed my mind. Many use express-device only for the purpose of finding the device type and do not want to use all the express stuff. Maybe it's time to move forward and do just that

**Comment by lennym** [comment]
Happy to put together a PR that uses `device` (a.k.a. the code ported out of this project by me yesterday) since I know what I left out. Give me ten mins...

**Comment by lennym** [comment]
Presto! #37

**Comment by rguerreiro** [comment]
Well...I don't have ownership of the "device" package and the current version of "device" depends from "express-device". Maybe I should create another package with another name?

**Comment by lennym** [comment]
The current version (as of yesterday) doesn't have the dependency anymore (see https://github.com/jimmybergman/device/blob/master/package.json)

I'd ask @jimmybergman to share ownership (which I imagine he'll be happy to do, since he was building on top of your code before, and was happy to merge code crediting you), but if you want to fork and publish a new package yourself then that's cool too. I just thought `device` was a good package since a) it has the best name, and b) was doing *exactly* what was required.

**Comment by rguerreiro** [comment]
Well then...the ball is on @jimmybergman 's side :)

**Comment by jimmybergman** [comment]
Absolutely no problem for me if device moves to beeing a package in this repo, any other repository handled by @rguerreiro or some other solution meaning that the code isn't in two places :-).

For now I added @rguerreiro as owner of the device package.

**Comment by rguerreiro** [comment]
Yesterday I made a little experiment called WIMD (stands for what is my device?). But I agree that calling it device is the best option. But do you agree that I change, a tiny bit, the API that you made in the device package? You can check my WIMD repo

**Comment by jimmybergman** [comment]
Well, I don't have a hard opinion and it is not a problem for myself, I was just thinking of not annoying users of the existing package. Although the old device package doesn't have a lot of users (it has some hundred downloads per month).

I.e. I would prefer if the existing API could be kept as well as the new one (i.e. making sure that require('device').useragent_is('useragent_string') returns like your parser.get_type(), but I have absolutely no problem with having the main API be like in the WIMD repo.

**Comment by lennym** [comment]
+1 for keeping the current API in place for backwards compatibility, and extending accordingly.

**Comment by rguerreiro** [comment]
Great! When I have some time off I'll publish the new device package with all of your suggestions. Thanks for all the input

**Comment by rguerreiro** [comment]
Done! New 0.3 version already published.

**Comment by lennym** [comment]
@rguerreiro @jimmybergman You guys are awesome!
