### ISSUE TITLE
FTLOG please added example of in-Express use

### ISSUE THREAD

**Issue by ORESoftware** [rguerreiro/express-device#39]
can someone please add an example of how this works in Express itself

```javascript
app.use(device.capture());

app.use(function(req,res,next){
   device.is_desktop ///  no indication that this is valid, please include example
   device.is_mobile /// no indication that this is valid, please include example to keep us from guessing
});

```

**Comment by ORESoftware** [comment]
well, I looked into your library code and found this:

```javascript
 res.locals.device_name = req.device.name;
```

so I ASSUME I can do this:

app.use(function(req,res,next){
   if(req.device.name === 'xyz'){

   }
});
```

if not I am going to be unhappy, please document better

**Comment by rguerreiro** [comment]
The request object has the device object, and just like it is documented it has 2 properties: type and name. You can use them the way you like, inside the middleware. Your example is valid. It's plain JavaScript.
