### ISSUE TITLE
Googlebot on smartphone classified as "phone" instead of "bot"

### ISSUE THREAD

**Issue by macinjosh32** [rguerreiro/express-device#40]
I'm seeing the following user agents being detected as "phone":

Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

Mozilla/5.0 (iPhone; CPU iPhone OS 83 like Mac OS X) AppleWebKit/600.1.4 (KHTML like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

More complete list here:
https://support.google.com/webmasters/answer/1061943?hl=en

Seems to me they should be categorized as "bot" to be consistent with the fact bot-ness trumps device type for desktop. What do you think?

**Comment by rguerreiro** [comment]
Seems to be an issue. I'll take a look

**Comment by rguerreiro** [comment]
Moved the issue to the right [repo](https://github.com/rguerreiro/device). All the device detection features were refactored to a different module called [device](https://www.npmjs.com/package/device).

Closing this one.

**Comment by rguerreiro** [comment]
Fixed on `device` package. Should use the **v0.3.4** to include the fix.
