### ISSUE TITLE
wget shows up as a phone

### ISSUE THREAD

**Issue by reality** [rguerreiro/express-device#41]
Thanks for your useful library, however there is one small issue: wget seems to be interpreted as a 'phone,' and I think it should be a 'bot.' Here is what I get when wgetting a simple page which simply res.sends the req.device:

```json
{"parser":{"options":{"emptyUserAgentDeviceType":"desktop","unknownUserAgentDeviceType":"phone","botUserAgentDeviceType":"bot","carUserAgentDeviceType":"car","parseUserAgent":true},"useragent":{"family":"Wget","major":"1","minor":"16","patch":"3","device":{"family":"Other","major":"0","minor":"0","patch":"0"},"os":{"family":"Other","major":"0","minor":"0","patch":"0"}}},"type":"phone","name":"Other"} 
```

If I perform the same experiment using curl, then it correctly returns as a bot.

This was tested using: express-device@0.4.2 useragent@2.1.8 and express@4.9.8

**Comment by rguerreiro** [comment]
Thanks for the feedback. I'll look into it

**Comment by rguerreiro** [comment]
Moved the issue to the device repo, since this functionality it's now implemented on that package

**Comment by rguerreiro** [comment]
New version (0.3.4) of ``device`` published to npm.
