### ISSUE TITLE
README a bit confusing (parseUserAgent default)

### ISSUE THREAD

**Issue by wamoyo** [rguerreiro/express-device#43]
This line:

> Example: iPhone. If the option parseUserAgent is set to false, then it will return an empty string

Makes it seem like the default is true. At least to me. Totally your call. I'd suggest:

> Example: iPhone. parseUserAgent is set to false by default and will return an empty string.

**Comment by rguerreiro** [comment]
And how about this:

> Example: iPhone. Unless you explicitly set **parseUserAgent** to true (which defaults to false, as mentioned below) it will always return an empty string.

**Comment by wamoyo** [comment]
Yeah, that's good too. Also, I never could get it to work : (

I followed the instructions in the README, npm installed useragent, required it, added the options object to device.capture() with the parseUserAgent set to true, but no luck. Still just the type property coming through.

**Comment by rguerreiro** [comment]
Did you tried like it's in here: https://github.com/rguerreiro/express-device/blob/master/example/app_with_parse.js ?

**Comment by wamoyo** [comment]
Yes. I'm looking into the code, and it looks like npm update didn't pull the latest version... Let me look closer.

**Comment by wamoyo** [comment]
Yeup, wrong version : ) My fault.
