### ISSUE TITLE
is_desktop is not defined :(

### ISSUE THREAD

**Issue by ouzhou** [rguerreiro/express-device#44]
it didn't work

**Comment by rguerreiro** [comment]
Strange, because it's [working on the tests](https://github.com/rguerreiro/express-device/blob/master/test/app/index_helpers.ejs).

Can you please post your code that reproduces the bug?

**Comment by AuspeXeu** [comment]
You need to add this line of code as explained in the documentation

`device.enableDeviceHelpers(app)`

**Comment by rguerreiro** [comment]
Closing it. Feel free to comeback if the issue arises
