### ISSUE TITLE
Make isBot orthogonal?

### ISSUE THREAD

**Issue by estaub** [rguerreiro/express-device#47]
Google has different bots for phone and desktop: see https://support.google.com/webmasters/answer/1061943?hl=en .

It'd be nice to be able to tell both whether it's a bot and which form-factor it's crawling for.

**Comment by rguerreiro** [comment]
@estaub That's a good idea. But at the moment I do not have the time to peek it up. Can you please submit a pull request? But please do it in my other package: [device](https://github.com/rguerreiro/device). expres-device uses that one under the hood.

**Comment by estaub** [comment]
Sorry, likewise, no time, and I decided to use something else that fit my needs better anyway.
