### ISSUE TITLE
code markup  with Native Node.js

### ISSUE THREAD

**Issue by pu3antasyah** [rguerreiro/express-device#48]
How to use it with native Node.js with res.write and create server only (without Express and ejs)?

example:

```
const device = require('express-device')

http.createServer(function(req, res) {
  res.writeHead('blablabla')
  if (is_desktop) {
     res.write('hi desktop)
  }
  res.end()
}
```

thanks in advance

**Comment by rguerreiro** [comment]
Please check my other package: [device](https://github.com/rguerreiro/device). It was made with that exact purpose
